'use client'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { loadCreativeServices, loadServiceProviders } from '@/lib/data'
import { defaultCreativeServices, defaultServiceProviders } from '@/lib/default-data'
import type { CreativeService, ServiceProvider } from '@/lib/types'
export default function ServicesPage(){
 const [providers,setProviders]=useState<ServiceProvider[]>(defaultServiceProviders); const [services,setServices]=useState<CreativeService[]>(defaultCreativeServices)
 useEffect(()=>{Promise.all([loadServiceProviders(),loadCreativeServices()]).then(([p,s])=>{setProviders(p);setServices(s)})},[])
 const active=useMemo(()=>services.filter(s=>s.active).sort((a,b)=>Number(b.featured)-Number(a.featured)||a.sortOrder-b.sortOrder),[services])
 return <main><section className="page-hero services-hero"><div className="container"><div className="eyebrow">Version6ix creative services</div><h1>Creative work<br/>built to perform.</h1><p>Blender animations, thumbnails and shortform edits created by Version6ix talent.</p></div></section><section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Our creators</div><h2>Meet the sellers</h2></div></div><div className="service-provider-grid">{providers.sort((a,b)=>a.sortOrder-b.sortOrder).map(provider=>{const own=active.filter(s=>s.providerId===provider.id);if(!own.length)return null;return <article className="service-provider-card" key={provider.id}>{provider.bannerImage&&<img className="service-provider-banner" src={provider.bannerImage} alt=""/>}<div className="service-provider-profile">{provider.profileImage?<img src={provider.profileImage} alt=""/>:<div className="service-provider-placeholder">{provider.displayName.slice(0,1)}</div>}<div><div className="eyebrow">{provider.acceptingWork?'Accepting work':'Currently unavailable'}</div><h2>{provider.displayName}</h2><strong>{provider.role}</strong><p>{provider.bio}</p><span>{provider.leadTime}</span></div></div><div className="service-mini-list">{own.map(service=><Link href={`/services/service?id=${encodeURIComponent(service.id)}`} key={service.id}><span>{service.category}</span><strong>{service.title}</strong><small>{service.priceLabel}</small></Link>)}</div></article>})}</div></div></section><section className="section services-all"><div className="container"><div className="section-head"><div><div className="eyebrow">Available now</div><h2>All services</h2></div><span>{active.length} offerings</span></div><div className="services-grid">{active.map(service=>{const provider=providers.find(p=>p.id===service.providerId);return <article className="service-card" key={service.id}><div className="eyebrow">{service.category}</div><h3>{service.title}</h3><p>{service.summary}</p><div className="service-card-meta"><span><small>Creator</small><strong>{provider?.displayName||'Version6ix'}</strong></span><span><small>Pricing</small><strong>{service.priceLabel}</strong></span></div><Link className="btn btn-primary service-card-cta" href={`/services/service?id=${encodeURIComponent(service.id)}`}><span>View service</span><b aria-hidden="true">↗</b></Link></article>})}</div></div></section></main>
}
